dokter-service:
  build: ./services/dokter-service
  ports:
    - "8002:8002"
  environment:
    - MONGO_URI=mongodb://mongo:27017/dokter_service_db
  depends_on:
    - mongo
     # lanjutkan 